### ISSUE TITLE
Failure to build on new tests

### ISSUE THREAD

**Issue by djw8605** [opensciencegrid/xrootd-monitoring-shoveler#56]
After merging #34, the tests are now failing.

**Comment by olifre** [comment]
Thanks for the ping!
My last rebase of the PR was upon https://github.com/opensciencegrid/xrootd-monitoring-shoveler/commit/134b5cbf00ec4c9639df588ef4f8307d100f1545 , i.e. at that point the tests were still working (i.e. after the default queue path change). 

I'll take a look and also increase `systemctl` output fot the tests.

**Comment by olifre** [comment]
@djw8605 The linked PR fixes it — apparently, setting the ownership of the home directory (and hence, queue directory) for the directories installed via `goreleaser` got lost somewhere. 
The good news is that the PR now also takes care of easing the debugging, i.e. adding more `systemctl` log output etc.
